name: Build

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js with cache
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: cd web && pnpm build
