name: Deploy and Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: deployment
    strategy:
      matrix:
        environment:
          - prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          output-credentials: true

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
        with:
          context: remix-app
          push: true
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/ecr-kanaru-me-${{ matrix.environment }}:latest
          provenance: false
          platforms: linux/arm64

      - name: Install Dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Latest Tag
        id: latest_tag
        run: |
          git fetch --tags
          echo "TAG=$(git tag -l --sort authordate | tail -n 1)" >> "$GITHUB_OUTPUT"

      - name: Check Terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}

      - name: Terraform Apply
        uses: gruntwork-io/terragrunt-action@v2
        env:
          TF_VAR_version_name: ${{ steps.latest_tag.outputs.TAG }}
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: apply
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}

      - name: Update Lambda Code
        run: |
          aws lambda update-function-code --function-name lambda-kanaru-me-app-${{ matrix.environment }} --image-uri ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/ecr-kanaru-me-${{ matrix.environment }}:latest
