name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  checks:
    name: Terraform Check
    runs-on: ubuntu-latest
    environment: deployment
    strategy:
      matrix:
        environment:
          - dev
          - prod
    defaults:
      run:
        working-directory: infrastructure/environments/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: deployment
    needs: [checks]
    strategy:
      matrix:
        environment:
          - dev
          - prod
    defaults:
      run:
        working-directory: infrastructure/environments/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}

      - name: Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          VERSION_NAME: ${{ github.ref_name }}
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: plan
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}
