name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

env:
  ROLE_TO_ASSUME: arn:aws:iam::760485329571:role/Github_OIDC
  AWS_REGION: ap-northeast-1

jobs:
  checks:
    name: Terraform Check
    runs-on: ubuntu-latest
    strategy:
      matrix: &matrix
        environment: [prod, dev]
    defaults: &defaults
      run:
        working-directory: infrastructure/environments/${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [checks]
    strategy:
      matrix: *matrix
    defaults: *defaults
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}

      - name: Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ matrix.environment }}
          tg_command: plan
