name: Terraform Commands

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Terraform command to run"
        required: true
        default: "plan"
        type: choice
        options:
          - "plan"
          - "apply"
          - "destroy"
      environment:
        description: "Environment to run Terraform in"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "prod"

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.command }}
    runs-on: ubuntu-latest
    environment: deployment
    defaults:
      run:
        working-directory: infrastructure/environments/${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}

      - name: Check Terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ github.event.inputs.environment }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}

      - name: Terraform ${{ github.event.inputs.command }}
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_dir: infrastructure/environments/${{ github.event.inputs.environment }}
          tg_command: ${{ github.event.inputs.command }}
          tf_version: ${{ vars.TF_VERSION }}
          tg_version: ${{ vars.TG_VERSION }}
